let Drinks = ["Oleato","Hot Coffes","Hot Teas", "Hot Drinks","Frappucchino Blended", "Cold Coffees", "Iced Teas", "Cold Drinks"]
let Food = ["Hot Breakfast", "Oatmeal & Yogurt", "Bakery", "Lunch", "Snacks & Sweets"]
let AtHomeCoffee = ["Whole Bean", "VIA Instant"]
let Merchandise = ["Cold Cups","Tumblers","Mugs","Water Bottles"]
let GiftCards = ["Happy Birthday", "Thank You", "Traditional"]